### ISSUE TITLE
Obsidian - When the collateral token is BNB, full liquidations will revert due to sending 0 amount

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#279] opened 2024-09-10 15:52 UTC
Obsidian

Medium

# When the collateral token is BNB, full liquidations will revert due to sending 0 amount

### Summary

BNB has a check in it's `transfer()` function to revert for 0 amounts

The issue is that during complete liquidations (taking all the collateral), the following [[code](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L178-L189)](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L178-L189) will send a 0 amount, which will revert the whole liquidation call

```solidity
// Transfer fee to treasury if it is non-zero
    if (vars.liquidationProtocolFeeAmount != 0) {
      uint256 liquidityIndex = collateralReserve.getNormalizedIncome();
      uint256 scaledDownLiquidationProtocolFee = vars.liquidationProtocolFeeAmount.rayDiv(liquidityIndex);
      uint256 scaledDownUserBalance = balances[params.collateralAsset][params.position].supplyShares;

      if (scaledDownLiquidationProtocolFee > scaledDownUserBalance) {
        vars.liquidationProtocolFeeAmount = scaledDownUserBalance.rayMul(liquidityIndex);
      }

      IERC20(params.collateralAsset).safeTransfer(IPool(params.pool).factory().treasury(), vars.liquidationProtocolFeeAmount);
    }

```

Even if the `vars.liquidationProtocolFeeAmount != 0`

since `scaledDownUserBalance == 0` (user has 0 collateral since the liquidator took all of it)

It will update `vars.liquidationProtocolFeeAmount == scaledDownUserBalance.rayMul(liquidityIndex)`, which is 0

Therefore trying to transfer the 0 amount will revert

### Root Cause

During a full liquidation, it will attempt to transfer a 0 amount [here](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L178-L189), which will revert the whole liquidation call

### Internal pre-conditions

Collateral token of user is BNB

### External pre-conditions

Liquidator attempts to take all the collateral

### Impact

Liquidation reverts, increasing the risk of accumulating bad debt

### Mitigation

Implement the 0 amount check right before the transfer to prevent this issue

**Comment by elhajin** [comment] 2024-10-05 17:14
This is invalid. The amount won't be zero as the comment stated:

> scaledDownUserBalance cannot be 0 if vars.liquidationProtocolFeeAmount != 0 because the liquidationProtocolFeeAmount is included in the _calculateAvailableCollateralToLiquidate() function

The PoC works because the fix applied from #228 is incorrect and introduces another bug. The fix suggests that the user collateral balance gets subtracted by (collateral seized + feeAmount) in _burnCollateralTokens(), which occurs before charging the fee amount. This leaves a state where feeAmount isn't zero, but the user collateralBalance is already reduced by the feeAmount. Then, we check against the user balance again to see if it's enough for feeAmount, which in this case can be zero.

The correct fix is mentioned in our duplicate of #288 (see issue #395). The feeAmount should only be subtracted from the user balance when it's decided inside the `if (vars.liquidationProtocolFeeAmount != 0) {}` block.

Please try running the same PoC with the correct fix here, not with the #228 fix, and it will never be 0:

```diff
if (vars.liquidationProtocolFeeAmount != 0) {
  uint256 liquidityIndex = collateralReserve.getNormalizedIncome();
  uint256 scaledDownLiquidationProtocolFee = vars.liquidationProtocolFeeAmount.rayDiv(liquidityIndex);
  uint256 scaledDownUserBalance = balances[params.collateralAsset][params.position].supplyShares;

  if (scaledDownLiquidationProtocolFee > scaledDownUserBalance) {
    vars.liquidationProtocolFeeAmount = scaledDownUserBalance.rayMul(liquidityIndex);
  }
+ DataTypes.ReserveCache memory collateralReserveCache = collateralReserve.cache(totalSupplies[params.collateralAsset]);
+ balances[params.collateralAsset][params.position].withdrawCollateral(
+   totalSupplies[params.collateralAsset], vars.liquidationProtocolFeeAmount, collateralReserveCache.nextLiquidityIndex
+ );
  console.log('amount fee to send : ', vars.liquidationProtocolFeeAmount);
  IERC20(params.collateralAsset).safeTransfer(IPool(params.pool).factory().treasury(), vars.liquidationProtocolFeeAmount);
}
```

**Comment by obou07** [comment] 2024-10-05 17:49
escalate 
per [comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/279#issuecomment-2395121771)

**Comment by sherlock-admin3** [comment] 2024-10-05 17:49
> escalate 
> per [comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/279#issuecomment-2395121771)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment] 2024-10-13 09:28
I agree with @Honour-d-dev and @elhajin comments.

As they mentioned, the `scaledDownUserBalance` user balance should not be zero if `liquidationProtocolFeeAmount` is non-zero, as it’s properly accounted for in the `_calculateAvailableCollateralToLiquidate()` function. This ensures the amount being transferred is valid and that the logic works correctly.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment] 2024-10-16 09:04
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment] 2024-10-16 09:04
Escalations have been resolved successfully!

Escalation status:
- [obou07](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/279/#issuecomment-2395131193): accepted

**Closed by WangSecurity** 2024-10-16 09:04 UTC
Labels: Escalated, Non-Reward
